#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\EtudiantController::index
#Etudiant
etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouterEtudiant
etudiantConsulter:
    path: /etudiant/consulter/{id}
    controller: App\Controller\EtudiantController::consulterEtudiant
etudiantLister:
    path: /etudiant/lister
    controller: App\Controller\EtudiantController::listerEtudiant
etudiantModifier:
    path: /etudiant/modifier/{id}
    controller: App\Controller\EtudiantController::modifierEtudiant
#Maison
maisonAjouter:
    path: /maison/ajouter
    controller: App\Controller\MaisonController::ajouterMaison
maisonConsulter:
    path: /maison/consulter/{code}
    controller: App\Controller\MaisonController::consulterMaison
maisonLister:
    path: /maison/lister
    controller: App\Controller\MaisonController::listerMaison
#Competence
competenceAjouter:
    path: /competence/ajouter
    controller: App\Controller\CompetenceController::ajouterCompetence
competenceConsulter:
    path: /competence/consulter/{id}
    controller: App\Controller\CompetenceController::consulterCompetence
competenceLister:
    path: /competence/lister
    controller: App\Controller\CompetenceController::listerCompetence
competenceModifier:
    path: /competence/modifier/{id}
    controller: App\Controller\CompetenceController::modifierCompetence
#Professeur
professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouterProfesseur
#professeurCompetenceAjouter:
#    path: /professeur/ajouterCompetence/{id}
#    controller: App\Controller\ProfesseurController::ajouterCompetenceProfesseur
professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur
professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur
professeurModifier:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifierProfesseur
#Note
noteConsulter:
    path: /note/consulter/{id}
    controller: App\Controller\NoteController::consulterNote
noteLister:
    path: /note/lister
    controller: App\Controller\NoteController::listerNote
#Stage
stageAjouter:
    path: /stage/ajouter
    controller: App\Controller\StageController::ajouterStage
stageConsulter:
    path: /stage/consulter/{id}
    controller: App\Controller\StageController::consulterStage
stageLister:
    path: /stage/lister
    controller: App\Controller\StageController::listerStage
stageModifier:
    path: /stage/modifier/{id}
    controller: App\Controller\StageController::modifierStage